# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('percent', models.IntegerField(default=0)),
            ],
        ),
    ]
